Import libraries

In [60]:
import pandas as pd
import numpy as np

Read datasets

In [61]:
data = pd.read_csv('https://raw.githubusercontent.com/TracyRenee61/Multiple-Time-Series-Predictions/main/Sales_Transactions_Dataset_Weekly.csv')
data = data.filter(regex=r'Product|W')
data

    Product_Code  W0  W1  W2  W3  W4  W5  ...  W45  W46  W47  W48  W49  W50  W51
0             P1  11  12  10   8  13  12  ...   10   12    3    7    6    5   10
1             P2   7   6   3   2   7   1  ...    1    1    4    5    1    6    0
2             P3   7  11   8   9  10   8  ...    5    7    8   14    8    8    7
3             P4  12   8  13   5   9   6  ...    4    6    8   14    8    7    8
4             P5   8   5  13  11   6   7  ...   12    6    6    5   11    8    9
..           ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...
806         P815   0   0   1   0   0   2  ...    0    0    1    0    0    2    0
807         P816   0   1   0   0   1   2  ...    2    4    5    5    5    6    5
808         P817   1   0   0   0   1   1  ...    2    2    0    0    0    4    3
809         P818   0   0   0   1   0   0  ...    1    1    0    0    0    2    0
810         P819   0   1   0   0   0   0  ...    0    0    0    0    0    0    1

[811 rows x 53 columns]

Check for null values

In [62]:
data.isnull().sum().sum()

0

Define X, y and X_test

In [63]:
code = data.Product_Code

data = data.drop(['Product_Code'], axis=1)

#split the dataset in two
# the last column is our label
y_train = data.iloc[:,-1:]
#drop last column of data
X_train = data.iloc[:, :-1]
#drop first colum of data
X_test = data.iloc[:,1:]
# lets have a look on the shape 
X_train.shape,y_train.shape, X_test.shape

((811, 51), (811, 1), (811, 51))

Scale

In [64]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Define the scaler 
scaler = StandardScaler().fit(X_train)
# Scale the train set
X_train = scaler.transform(X_train)
# Scale the validation set
#X_val = scaler.transform(X_val)
# Scale the test set
X_test = scaler.transform(X_test)

Define model

In [65]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=3000, max_depth=15, random_state=1, verbose=True).fit(X_train, y_train)
y_pred = model.predict(X_train)
y_pred = y_pred.astype(int)
y_pred

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:   37.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:    0.6s finished

array([ 9,  2,  7,  7,  9,  5,  2,  9, 13, 21, 17,  4,  6, 16, 20, 22, 24,
       23, 27,  9,  6,  6,  1, 17, 21, 17, 26, 23, 14, 22,  7,  7, 13, 25,
       26, 20, 26, 24, 24, 21, 25, 18, 26, 19, 21, 17, 21, 25, 23,  8, 12,
       21,  7, 25, 24, 20, 21, 28, 11, 22, 24, 12, 20, 19,  9, 23, 24,  7,
       22, 27,  7, 22, 18, 10, 23, 18,  5, 21, 21, 23, 12,  7, 29, 21, 18,
       24, 23, 23, 25, 19,  9, 20,  9,  9, 14, 22, 24,  5, 10, 19, 17, 27,
        7,  4,  4, 17, 20,  4,  9,  7,  8, 31, 19,  8, 10, 11,  3, 10, 20,
       27, 11, 11,  4,  5,  7,  5,  1, 22, 21, 18, 23, 21, 19, 24, 18, 19,
       26, 23, 23, 26, 23, 24, 23, 11,  8, 11,  5,  6,  6,  4,  4, 11,  9,
        7,  4,  4,  6,  4,  6, 10,  5, 11,  4, 10, 10, 10, 26, 19, 30, 28,
        8, 24, 18, 23, 21, 17, 26, 24, 24, 18, 17, 21, 20, 27, 26, 20, 26,
       24, 22, 27, 23, 28, 20, 25,  3, 26, 10, 15,  3, 25,  4, 22,  7,  4,
       18,  4, 10, 37, 13, 15, 13,  1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  6,
        0,  1,  0,  0,  0, 31, 41, 25, 10,  3, 16, 12, 22, 16, 28,  5,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  0, 19, 13, 27,  1,  2,  0,
        1,  5,  5,  3,  6,  3,  7,  3,  6, 11,  5,  2,  5,  3, 10,  6,  6,
        7,  3,  8,  4,  4,  5,  5, 12,  8,  3,  5,  5,  7,  7,  3,  3,  4,
        9,  5,  2,  2,  5,  4,  5,  5,  9,  9, 10,  5,  4,  4,  5,  2,  1,
        7,  5,  4,  3,  6,  0,  0,  0,  1,  0,  0,  0,  0,  0,  6,  2,  4,
        8,  2,  4,  2,  0, 22,  6,  5,  5, 10,  4,  4,  3,  4,  3,  1,  2,
        1,  0,  1,  0,  0,  0,  0,  0,  1,  0,  7,  4,  4,  2,  7,  9,  4,
        5,  3,  5, 12, 18, 21, 21,  7,  1, 23, 13, 28, 21, 20, 20, 58, 27,
       23,  4, 15,  6,  4,  2,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,
        0, 11, 19, 12, 13, 12,  7, 24, 13,  8,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  2,  2,  1,  2,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  3,  2,  2,
        3,  0,  4,  1,  1,  3,  8, 20, 17, 10,  4,  7, 20, 11, 10, 14, 23,
       11,  4,  4, 11,  6,  7, 16, 21, 13, 14, 14, 26, 12,  6, 12, 27, 31,
       21, 15, 11, 21, 14, 15, 20, 19, 10, 10, 13, 11, 13, 25, 11, 15, 14,
       21,  6, 13, 32, 10, 32, 19, 21, 21,  9, 18, 16, 12, 10, 11, 21, 14,
       12, 27, 20,  7,  8,  8,  4, 18,  9, 25, 27, 18, 14, 14,  4,  5,  9,
        9,  9, 23,  3,  5,  2,  4,  9,  4,  5,  0,  1,  0,  1,  0,  0,  6,
        4,  2,  4,  4,  1, 10,  5,  4,  1,  6,  6,  5,  3,  4,  3,  8,  4,
       20, 12,  5,  3,  1,  0,  1,  3,  2,  0,  3,  8,  5,  8, 16, 29, 10,
       34,  5, 19, 29, 22, 20, 27, 25, 23,  5,  9, 10, 11,  8,  8,  6,  8,
       10, 12,  9,  7, 13,  4, 20,  0, 20,  4,  5,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,
        0,  0,  2,  0,  0,  6, 16,  8,  8,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  4,  1,  0,  2,  0,  0,  4,  6,  0,  0,  0,  1,  3,  1,  4,  5,
       13,  7,  1,  2,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  2,  9,  3,  0,  0,  0,  4,  2,  1,  0,  5,  4,  2,  1,
        0,  0,  2,  3,  0,  7,  5,  6,  2,  1,  0,  1,  2,  2,  2,  1,  0,
        1,  1,  0,  0,  0,  4,  0,  9,  3,  2,  2,  9,  5,  0,  0,  0,  0,
        0,  0,  0,  1,  0,  0,  0, 27,  3, 22,  4,  3,  2,  5,  8,  7,  3,
       11,  3,  7,  2,  1,  4,  4,  4,  9,  3,  9,  2,  7,  2,  3,  7,  3,
       10,  2,  0,  5,  3,  4,  9,  0,  5,  2,  0,  0])

In [66]:
print(model.score(X_train, y_train))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

0.9794312749689092

[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:    0.6s finished

Make predictions

In [67]:
prediction = model.predict(X_test)
prediction = prediction.astype(int)
prediction

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 3000 out of 3000 | elapsed:    0.6s finished

array([ 8,  5, 10,  9,  8,  5,  5,  8, 11, 21, 13,  5,  9, 15, 23, 23, 22,
       22, 24,  8,  9,  9,  5, 21, 23, 12, 23, 24, 14, 20,  8,  8, 12, 22,
       24, 24, 24, 23, 23, 24, 22, 24, 22, 22, 24, 24, 22, 26, 22,  9, 18,
       24,  5, 23, 24, 21, 21, 22, 10, 23, 23, 14, 22, 23,  9, 23, 22,  8,
       22, 22,  9, 23, 20,  8, 28, 22,  5, 23, 22, 22, 12,  9, 24, 24, 22,
       23, 21, 22, 21, 24,  8, 23,  8,  9, 15, 22, 21,  5, 10, 15, 22, 23,
        8,  5,  4, 13, 22,  4,  9,  9,  5, 25, 24,  8, 11, 10,  4, 10, 23,
       24, 10,  8,  5,  6,  8,  6,  3, 23, 23, 39, 21, 22, 24, 22, 22, 24,
       22, 24, 22, 24, 24, 22, 22, 10,  8,  9,  9,  5,  9,  5,  5,  9,  8,
        8,  5,  5,  8,  5,  5,  7,  6,  8,  6, 10,  9,  8, 22, 24, 23, 22,
        9, 23, 21, 24, 23, 22, 23, 21, 24, 21, 22, 22, 23, 23, 23, 23, 21,
       24, 24, 21, 20, 22, 23, 23,  6, 25,  8, 16,  4, 21,  5, 19,  6,  4,
       18,  5,  7, 29, 13, 16, 13,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  3,
        0,  1,  0,  0,  0, 23, 31, 21, 12,  4, 13, 12, 22, 19, 22,  4,  1,
        1,  0,  0,  0,  0,  0,  0,  0,  2,  2,  1, 21, 11, 24,  2,  2,  0,
        1,  6,  5,  5, 11,  6,  6,  5,  4, 10,  6,  5,  6,  5,  8,  5,  5,
        5,  5, 10,  5,  5,  5,  5, 11,  7,  5,  5,  5, 10,  5,  6,  5,  4,
       11,  5,  5,  5,  4,  6,  5,  5,  8, 10, 10,  4,  4,  4,  4,  3,  2,
        4,  4,  4,  3,  5,  1,  0,  1,  0,  0,  0,  0,  0,  0,  6,  3,  3,
        6,  2,  4,  2,  1, 17,  4,  5,  4,  7,  5,  5,  4,  4,  4,  3,  1,
        1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  5,  4,  4,  4,  4,  7,  3,
        5,  4,  4, 11, 17, 17, 20,  5,  4, 20, 13, 23, 19, 21, 18, 33, 21,
       21,  5, 11,  5,  4,  2,  1,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,
        0, 10, 17,  8, 12,  7,  4, 20, 13,  9,  1,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  1,  1,  0,  1,  1,  0,  0,  1,  1,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  3,  1,  3,
        2,  1,  3,  1,  1,  5, 10, 20, 15, 11,  5, 10, 19, 10, 11, 14, 19,
       10,  5,  5, 11,  7,  6, 16, 19, 14, 17, 14, 20,  9,  8, 10, 25, 23,
       20, 16, 11, 20, 14, 12, 20, 15, 11, 11, 13, 10, 14, 20, 10, 15, 14,
       20,  5, 12, 23, 11, 21, 17, 22, 15,  9, 21, 12, 12, 12, 13, 20, 15,
       12, 24, 24, 10, 10,  9,  5, 20, 11, 18, 25, 15, 14, 11,  5,  7,  9,
        7,  8, 21,  5,  5,  3,  3,  7,  3,  5,  1,  0,  1,  2,  0,  0,  4,
        4,  4,  4,  4,  3,  9,  4,  4,  4,  4,  4,  2,  4,  4,  4,  6,  4,
       19,  9,  5,  4,  2,  1,  0,  3,  3,  0,  1,  5,  4,  5, 19, 22,  8,
       23,  6, 25, 23, 24, 24, 22, 23, 24,  9,  8,  9,  9,  9, 10,  7,  7,
       10, 12, 11,  8, 14,  5, 19,  0, 21,  4,  4,  0,  0,  0,  0,  0,  0,
        1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  1,  1,  0,  0,
        0,  0,  2,  2,  0,  5, 12,  7,  6,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  4,  2,  1,  1,  1,  0,  3,  4,  0,  0,  0,  1,  4,  3,  2,  5,
        9,  5,  2,  5,  3,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  2,  6,  2,  0,  0,  1,  3,  1,  1,  1,  2,  5,  2,  0,
        0,  0,  2,  3,  0,  7,  4,  6,  1,  1,  0,  1,  3,  2,  2,  0,  0,
        0,  0,  0,  0,  0,  4,  0,  7,  3,  2,  3,  6,  2,  0,  0,  0,  0,
        0,  0,  1,  0,  0,  1,  0, 20,  5, 18,  5,  3,  4,  2,  4,  6,  4,
        7,  3,  5,  1,  1,  5,  5,  4,  6,  3,  5,  2,  4,  4,  4,  7,  3,
        8,  1,  0,  5,  2,  4,  7,  1,  6,  1,  1,  0])

In [68]:
#create dataframe
output = pd.DataFrame({'code': code, 'sales': prediction})
#create csv
output.to_csv('submission.csv', index=False)
#upload submission
submission = pd.read_csv("submission.csv")
submission

     code  sales
0      P1      8
1      P2      5
2      P3     10
3      P4      9
4      P5      8
..    ...    ...
806  P815      1
807  P816      6
808  P817      1
809  P818      1
810  P819      0

[811 rows x 2 columns]